services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: lab3_app
    environment:
      MONGODB_URI: mongodb://mongo:27017
      MONGODB_DB: job_platform
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: lab3_mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
